apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8scluster1
  region: us-east-1a

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-1
  spot: false
  ssh:
    publicKeyName: k8s