---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: cart-config
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: cart-pod
  labels:
    tier: app
spec:
  containers:
  - name: cart-container
    image: udaysha10/cart:k8
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: cart-config
    
---
apiVersion: v1 
kind: Service
metadata:
  name: cart
spec:
  selector:
    tier: app
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
---

