---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: shipping-config
data:
  CART_ENDPOINT: "cart"
  DB_HOST: "mysql"
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping-pod
  labels:
    tier: app
    name: shipping 
spec:
  containers:
  - name: shipping
    image: udaysha10/shipping:k8
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: shipping-config
---
apiVersion: v1 
kind: Service
metadata:
  name: shipping
spec:
  selector:
    tier: app
    name: shipping
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
---

