---
apiVersion: v1 
kind: Pod
metadata:
  name: rabbitmq-pod
  labels: 
    tier: db
    name: rabbitmq
spec:
  containers: 
  - name: rabbitmq
    image: rabbitmq
    imagePullPolicy: Always
    ports:
      - containerPort: 5672
      - containerPort: 15672
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    tier: db
    name: rabbitmq
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: http
---
