---
apiVersion: v1
kind: Pod
metadata:
  name: ratings-pod
  labels:
    tier: app
    name: ratings 
spec:
  containers:
  - name: ratings
    image: udaysha10/ratings:k8
    imagePullPolicy: Always
    ports:
     - containerPort: 80
    
---
apiVersion: v1 
kind: Service
metadata:
  name: ratings
spec:
  selector:
    tier: app
    name: ratings
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
---

