---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data: 
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    tier: db
    name: mysql
spec: 
  containers:
  - name: mysql
    image: udaysha10/mysql:v1
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretRef:
        name: mysql-secret
    ports:
     - containerPort: 3306
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
spec:
  selector:
    tier: db
    name: mysql
  ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
---


     

