apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
data: 
  MONGO_URL: "mongodb://mongodb:80/catalogue"

---
apiVersion: v1 
kind: Pod
metadata:
  name: catalogue-pod
  labels:
    tire: app
    name: catalogue
spec:
  containers:
  - name: catalogue-container
    image: udaysha10/catalogue:k8
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: catalogue-config
    resources:
      requests:
        cpu: "150m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "200Mi"
---
apiVersion: v1 
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    tire: app
    name: catalogue
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080


