---
apiVersion: v1 
kind: Pod
metadata:
  name: catalogue-pod
  labels:
    tire: app
    name: catalogue
spec:
  containers:
  - name: catalogue-container
    image: udaysha10/catalogue:k8
    imagePullPolicy: Always
    
    resources:
      requests:
        cpu: "150m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "200Mi"
---
apiVersion: v1 
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    tire: app
    name: catalogue
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080


