---
apiVersion: v1 
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    tire: db
    name: mongodb
spec:
  containers:
  - name: mongodb-container
    image: udaysha10/mongodb:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 27017
    
---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    tire: db
    name: mongodb
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017


