---
apiVersion: v1 
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    tire: db
    name: mongodb
spec:
  containers:
  - name: mongodb-container
    image: udaysha10/mongodb:k8
    imagePullPolicy: Always
    ports:
    - containerPort: 27017
    resources:
      requests:
        cpu: "150m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "200Mi"
---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    tire: db
    name: mongodb
  ports:
   - protocol: TCP
     port: 80
     targetPort: 27017


