---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    tier: app
spec:
  containers:
  - name: user
    image: udaysha10/user:k8
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: user-config
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    tier: app
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
  
---
