apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: db
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: Always
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    tier: db
  ports: 
   - protocol: TCP
     port: 80
     targetPort: 6379
---
