---
apiVersion: v1 
kind: Pod
metadata:
  name: web-pod
  labels:
    tire: frontend
    name: web
spec:
  containers:
  - name: web-container
    image: udaysha10/web:k8
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "150m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "200Mi"
---
apiVersion: v1 
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    tire: frontend
    name: web
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80


